[package]
name = "jetkit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
eyre = "0.6.12"
hex = "0.4.3"
secp256k1 = { version = "0.30.0", features = ["rand"] }
sha3 = "0.10.8"
zeroize = "1.8.1"

[[bin]]
name = "ses"
path = "src/ses/main.rs"
